# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: c91b2bbdf98a1a3b60ebc27b5c04b545f4aa0382e51f482c31074d935b1fa99ed186d00503cdf707ebf3895444db1b0d5b622b301df46d7b10e82ae3e9186905

test:
  secret_key_base: 7fbe080f04c513c2275b277fc5d5a4a4982d73070f6e7aba706fa0f0b9745eeffea2bd67d2ba4a31c68fc0342688c0a8d7269ee800c85b3a5175b64d0f6dabef

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
